name: fma
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - pip:
    - hurst==0.0.5 #have to force a pip install as hurst is not supported in conda channels
  - numpy==1.19.1
  - quandl==3.5.2
  - matplotlib==3.3.1
  - pytest==6.0.2
  - scipy==1.5.2
